---
title: "BSDS 100 Case Study"
author: "Jacques Sham & Charles Siu"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(fig.width = 10)
```

```{r libraries, include = F, warning = F, message = F}
suppressMessages(library(tidyverse))
suppressMessages(library(magrittr))
library(zoo)
library(ggplot2)
library(scales)
library(maps)
library(mapdata)
library(grid)
library(treemapify)
```

```{r init, include = F}
## Set the working dir according to who is working
curr_wd <- strsplit(getwd(), "/")[[1]]
if ("chunheisiu" %in% curr_wd) {
  setwd("/Users/chunheisiu/Dropbox/Documents/USF/2018_Spring/BSDS_100/USF-BSDS100-CaseStudy")
} else if ("jacquessham" %in% curr_wd) {
  setwd("/Users/jacquessham/Documents/GitHub/USF-BSDS100-CaseStudy")
} else {
  wd <- readline(prompt = "You're not Jacques or Charles! Enter the path to the data: ")
  setwd(wd)
}

## Read the data
data <- suppressMessages(read_csv("Air_Traffic_Passenger_Statistics.csv"))
```

## Part 1: Executive Summary

!!DOTO: No more than 250 words explaining, with extreme concision, your data and findings!!


## Part 2: Introduction to the Data

```{r cleanup}
# First, let's clean the data.
# Rename the column names
names(data) <- c("date", "operAirline", "operCode", "airline", "code", "isDomestic",
                 "region", "type", "category", "terminal", "area", "pax")

# Drop operating airline and code columns since they are insignificant
data %<>%
  select(-c(operAirline, operCode))

# Convert isDomestic to boolean
data$isDomestic %<>% recode("Domestic" = T, "International" = F)

# Reformat the dates into Date objects
data$date %<>% 
  as.character() %>% 
  as.yearmon("%Y%m") %>% 
  as.Date()

# Get month and year values
data %<>% 
  mutate(month = date %>% format("%m") %>% factor(labels = month.name),
         year = date %>% format("%Y") %>% as.numeric())

# Remove data from 2005 for easy comparison
data %<>% filter(year != 2005)

data$region %<>% recode("Central America" = "Latin America",
                        "South America" = "Latin America")
data$category %<>% recode("Other" = "Full Service") 

## airline = Published Airline, mother company airline
## code = Published Airline Code, code for variable "airline"
## isDomestic: If the flight is domestic,T; if international: F
## region: Geom region
## type: activity type; Deplaned means arrival, Enplaned means departure, Thru / Transit is other 
## category: Airline price type; Low fare is Low cost carrier, else are others
## terminal: SFO terminal
## area: area within SFO terminal
## pax: passenger count of given row
```

```{r cleanup2}
## Need to clean up incorrect data
## Below has the list of low cost carrier
## https://www.icao.int/sustainability/Documents/LCC-List.pdf

# Merge "United Airlines - Pre 07/01/2013" to "United Airlines"
data$airline %<>% recode("United Airlines - Pre 07/01/2013" = "United Airlines")

# Remove the strip of "Emirates "
data$airline %<>% recode("Emirates " = "Emirates")

# Some airlines were wrongly identified in category
# Convert the below airlines to full service/Low Fare
full_svc_airline <- c("Air China", "Air India Limited", "Air New Zealand", "Air Pacific Limited dba Fiji Airways",
                      "Emirates", "United Airlines", "Virgin America", "Volaris Airlines", "Delta Air Lines",
                      "US Airways")

lcc_svc_airline <- c("XL Airways France", "WOW Air", "WestJet Airlines")

data %<>%
  mutate(cat_temp = ifelse(airline %in% full_svc_airline, "Full Service", 
                    ifelse(airline %in% lcc_svc_airline, "Low Fare", as.character(category)))) %>% 
  mutate(category = as.factor(cat_temp))

# Change terminal into factor
data %<>%
  mutate(terminal = factor(terminal, levels = c("Terminal 1", "Terminal 2", "Terminal 3", "International", "Other")))
```


### I. Overview

```{r global_vars}
million <- 1000000
```


```{r global_theme}
format_title <- theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
format_legend_title <- theme(legend.title = element_text(face = "bold"))
```


#### Overall passenger traffic between 2006 and 2017

```{r annual_pax_trend}
data %>% 
  ggplot() +
  geom_bar(aes(x = year, y = pax / million, fill = month), stat = "identity") +
  theme_minimal() +
  scale_x_continuous(name = "Year", breaks = seq(2006, 2017, by = 1)) +
  scale_y_continuous(name = "Passengers (Millions)") +
  scale_fill_discrete(name = "Month") +
  ggtitle("The Monthly Average Passengers Count") +
  format_title +
  format_legend_title
```

#### Average passenger traffic between 2006 and 2017

```{r average_month_pax}
data %>%
  group_by(isDomestic, month) %>%
  summarise(avg_pax = round(mean(pax), digit = 0)) %>% 
  ggplot(aes(x = factor(month, labels = month.abb), y = avg_pax, fill = isDomestic)) +
  geom_bar(stat = "identity", alpha = 0.8) +
  theme_minimal() +
  scale_y_continuous(labels = comma) + 
  scale_fill_discrete(name = "Destination", label = c("International","Domestic")) +
  labs(x = "Month", y = "Passengers") +
  ggtitle("Monthly Average Passengers Count") +
  geom_text(aes(label = format(avg_pax, big.mark = ",")), size = 2.75,
            position = position_stack(vjust = 0.5), colour = "white") +
  format_title +
  format_legend_title
```

#### Activity Type

```{r traffic_type}
total_traffic <- data %>%
  summarise(total_traffic = sum(pax)) %>% 
  as.numeric()

data %>%
  group_by(type) %>%
  summarise(traffic = sum(pax)) %>% 
  ggplot(aes(x = "", y = traffic, fill = type)) +
  geom_bar(width = 1 , stat = "identity") +
  geom_text(aes(x = 1, y = cumsum(traffic) - traffic / 2, label = percent(traffic / total_traffic))) +
  coord_polar(theta = "y") +
  theme_void() +
  scale_fill_brewer(palette = "Set2", name = "Activity Type", label = c("Arrival", "Departure", "Transit")) +
  ggtitle("Percentage of Airplane Activities") +
  format_title +
  format_legend_title
```


### II. Destination

```{r map_setup}
# Load the world map and cities
world <- map_data("world")
cities <- world.cities

# Retrieve the information of SF
sf <- world.cities %>%
  filter(name == "San Francisco" & country.etc == "USA")

# Derive the cities and corresponding regions
cities %<>%
  filter(
    (name == "Adelaide" & country.etc == "Australia") |
    (name == "La Paz" & country.etc == "Bolivia") |
    (name %in% c("Saint Louis", "La Ronge",
                 "Riyadh", "Mexico City", "Shenzhen", "Ostrava"))
    ) %>% 
  mutate(region =
           ifelse(name == "Adelaide", "Australia / Oceania",
           ifelse(name == "Saint Louis", "US",
           ifelse(name == "La Ronge", "Canada",
           ifelse(name == "La Paz", "Latin America",
           ifelse(name == "Riyadh", "Middle East",
           ifelse(name == "Mexico City", "Mexico",
           ifelse(name == "Shenzhen", "Asia",
           ifelse(name == "Ostrava", "Europe", NA))))))))
  ) %>% 
  full_join(y = data %>%
              mutate(region = as.character(region)) %>% 
              group_by(region, type) %>%
              summarize(pax = sum(pax)), by = "region") %>% 
  mutate(
    origin.lat = ifelse(type == "Enplaned", sf$lat, lat),
    origin.long = ifelse(type == "Enplaned", sf$long, long),
    dest.lat = ifelse(type == "Enplaned", lat, sf$lat),
    dest.long = ifelse(type == "Enplaned", long, sf$long)
  ) %>% 
  filter(type != "Thru / Transit")

cities_na <- cities %>% filter(region %in% c("US", "Canada", "Mexico"))
cities_intl <- cities %>% filter(!(region %in% c("US", "Canada", "Mexico")))
```

```{r draw_map}
# Geom objects for drawing static objects
draw_sf_point <- geom_point(x = sf$long, y = sf$lat, color = "red", size = 3)

draw_na_sf_label <- geom_text(aes(x = sf$long, y = sf$lat, label = "SFO"),
                           hjust = 1, nudge_x = -2, color = "red", size = 3)

draw_intl_sf_label <- geom_text(aes(x = sf$long, y = sf$lat, label = "SFO"),
                           hjust = 1, nudge_x = -5, color = "red", size = 3)

draw_color_legend <- scale_color_discrete(name = "Activity Type",
                                          labels = c("Arriving SFO", "Departing SFO"))

draw_size_legend <- scale_size_continuous(trans = "log10", guide = F)

# Functions for drawing curves, points and labels
draw_flight_curve <- function(d) {
  geom_curve(data = d %>% filter(type %in% c("Deplaned", "Enplaned")),
                           aes(x = origin.long, y = origin.lat,
                               xend = dest.long, yend = dest.lat,
                               color = type, size = pax),
                           curvature = 0.5, lineend = "round",
                           alpha = 0.75, arrow = arrow(length = unit(0.025, "npc")))
}

draw_city_points <- function(d) {
  return (geom_point(data = d, aes(x = long, y = lat), color = "black", size = 3))
}

draw_na_city_labels <- geom_text(data = cities_na, aes(x = long, y = lat, label = region),
                              hjust = 0, nudge_x = 2, nudge_y = -0.5,
                              color = "black", size = 3)

draw_intl_city_labels <- geom_text(data = cities_intl, aes(x = long, y = lat, label = region),
                              hjust = 0, nudge_x = 3.5, nudge_y = -1,
                              color = "black", size = 3)

draw_na_enplaned_labels <- geom_label(data = cities_na %>% filter(type == ("Enplaned")),
                                  aes(x = long, y = lat, label = format(pax, big.mark = ","), color = type),
                                  hjust = 0, nudge_x = 2, nudge_y = -2.5, size = 3, show.legend = F)

draw_na_deplaned_labels <- geom_label(data = cities_na %>% filter(type == ("Deplaned")),
                                 aes(x = long, y = lat - 4, label = format(pax, big.mark = ","), color = type),
                                 hjust = 0, nudge_x = 2, nudge_y = -.75, size = 3, show.legend = F)

draw_intl_enplaned_labels <- geom_label(data = cities_intl %>% filter(type == ("Enplaned")),
                                  aes(x = long, y = lat, label = format(pax, big.mark = ","), color = type),
                                  hjust = 0, nudge_x = 3.5, nudge_y = -7, size = 3, show.legend = F)

draw_intl_deplaned_labels <-geom_label(data = cities_intl %>% filter(type == ("Deplaned")),
                                 aes(x = long, y = lat - 4, label = format(pax, big.mark = ","), color = type),
                                 hjust = 0, nudge_x = 3.5, nudge_y = -9.5, size = 3, show.legend = F)

format_theme <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  legend.position = "bottom",
  legend.background = element_rect(fill = "gray90", size = 0),
  legend.title = element_text(face = "bold")
  )
```

```{r draw_na_map, fig.height = 8}
world %>% 
  filter(region %in% c("USA", "Canada", "Mexico")) %>% 
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group), fill = "darkgray") +
  draw_flight_curve(cities_na) +
  draw_city_points(cities_na) +
  draw_na_city_labels +
  draw_sf_point +
  draw_na_sf_label +
  draw_na_enplaned_labels +
  draw_na_deplaned_labels +
  coord_fixed(1.3) +
  theme_minimal() +
  draw_color_legend +
  draw_size_legend +
  scale_fill_brewer(palette = "Set2") +
  scale_x_continuous(limits = c(-170, -50)) +
  ggtitle("Passengers Count by North American Destinations") +
  format_theme +
  format_title
```

```{r draw_intl_map, fig.height = 8}
world %>% 
  filter(region != "Antarctica") %>% 
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group), fill = "darkgray") +
  draw_flight_curve(cities_intl) +
  draw_city_points(cities_intl) +
  draw_intl_city_labels +
  draw_sf_point +
  draw_intl_sf_label +
  draw_intl_enplaned_labels +
  draw_intl_deplaned_labels +
  coord_fixed(1.3) +
  theme_minimal() +
  draw_color_legend +
  draw_size_legend +
  scale_x_continuous(limits = c(-170, 200)) +
  scale_y_continuous(limits = c(-60, 90)) +
  ggtitle("Passengers Count by International Destinations") +
  format_theme +
  format_title
```


### III. Airline Overview

```{r top5_dom_list}
# Filter the top 5 airlines by domestic passenger count
top5_dom_list <- data %>%
  filter(isDomestic) %>%
  group_by(airline) %>%
  summarise(total_pax = sum(pax)) %>%
  top_n(5, total_pax) %>%
  arrange(total_pax) %>% 
  select(-total_pax)

# Combine and compute the other airlines
other_dom_airline <- data %>% 
  filter(!(airline %in% top5_dom_list$airline)) %>% 
  group_by(year) %>% 
  summarise(sum = sum(pax)) %>% 
  mutate(airline = "Other Airlines") %>% 
  select(airline, year, sum)
```

```{r top5_dom_area}
data %>%
  group_by(airline, year) %>% 
  summarize(sum = sum(pax)) %>% 
  right_join(top5_dom_list, by = "airline") %>%
  ungroup() %>% 
  rbind(other_dom_airline) %>%
  rbind(data %>%
          group_by(airline) %>%
          right_join(top5_dom_list, by = "airline") %>%
          summarize(year = min(year) - 1) %>%
          filter(year == min(data$year)) %>%
          mutate(sum = 0)) %>% 
  mutate(airline = factor(airline, levels = rbind(top5_dom_list, "Other Airlines")$airline)) %>% 
  ggplot() +
  geom_area(aes(x = year, y = sum / million, fill = airline), alpha = 0.75) +
  scale_x_continuous(name = "Year", breaks = seq(min(data$year), max(data$year), by = 1)) +
  scale_y_continuous(name = "Passengers (Millions)") +
  scale_fill_brewer(name = "Airline", palette = "Set2") +
  theme_minimal() +
  ggtitle("Domestic Passengers Count by Airline") +
  format_title +
  format_legend_title
```

```{r top_intl_list}
# Filter the top 5 airlines by international passenger count
top5_intl_list <- data %>%
  filter(!isDomestic) %>%
  group_by(airline) %>%
  summarise(total_pax = sum(pax)) %>%
  top_n(5, total_pax) %>%
  arrange(total_pax) %>% 
  select(-total_pax)

# Combine and compute the other airlines
other_intl_airline <- data %>% 
  filter(!(airline %in% top5_intl_list$airline)) %>% 
  group_by(year) %>% 
  summarise(sum = sum(pax)) %>% 
  mutate(airline = "Other Airlines") %>% 
  select(airline, year, sum)
```

```{r top5_intl_area}
data %>%
  group_by(airline, year) %>% 
  summarize(sum = sum(pax)) %>% 
  right_join(top5_intl_list, by = "airline") %>%
  ungroup() %>% 
  rbind(other_intl_airline) %>%
  rbind(data %>%
          group_by(airline) %>%
          right_join(top5_intl_list, by = "airline") %>%
          summarize(year = min(year) - 1) %>%
          filter(year == min(data$year)) %>%
          mutate(sum = 0)) %>% 
  mutate(airline = factor(airline, levels = rbind(top5_intl_list, "Other Airlines")$airline)) %>% 
  ggplot() +
  geom_area(aes(x = year, y = sum / million, fill = airline), alpha = 0.75) +
  scale_x_continuous(name = "Year", breaks = seq(min(data$year), max(data$year), by = 1)) +
  scale_y_continuous(name = "Passengers (Millions)") +
  scale_fill_brewer(name = "Airline", palette = "Set3") +
  theme_minimal() +
  ggtitle("International Passengers Count by Airline") +
  format_title +
  format_legend_title
```

```{r top_region}
top_area <- data %>%
  group_by(region, airline) %>%
  summarise(pax_flow = sum(pax)) %>%
  top_n(1, pax_flow)
```

### IV. Terminal Traffic

```{r terminal_domestic}
data %>%
  filter(isDomestic, !is.na(code)) %>%
  group_by(terminal, airline, code) %>%
  summarise(all_pax = sum(pax)) %>% 
  ggplot(aes(area = all_pax, fill = terminal, label = code, group = airline)) +
  geom_treemap() +
  geom_treemap_text(colour = "white", place = "centre") +
  scale_fill_brewer(name = "Terminal", palette = "Set2") +
  ggtitle("Domestic Passengers Count by Airline and Terminal") +
  format_title +
  format_legend_title
```

```{r terminal_international}
data %>%
  filter(!isDomestic, !is.na(code)) %>%
  group_by(terminal, airline, code) %>%
  summarise(all_pax = sum(pax)) %>% 
  ggplot(aes(area = all_pax, fill = terminal, label = code, group = airline)) +
  geom_treemap() +
  geom_treemap_text(colour = "white", place = "centre") +
  scale_fill_brewer(name = "Terminal", palette = "Set2") +
  ggtitle("International Passengers Count by Airline and Terminal") +
  format_title +
  format_legend_title
```


```{r terminal}
data %>%
  filter(!is.na(code)) %>%
  group_by(terminal, airline, code) %>%
  summarise(all_pax = sum(pax)) %>% 
  ggplot(aes(area = all_pax, fill = terminal, label = code, group = airline)) +
  geom_treemap() +
  geom_treemap_text(colour = "white", place = "centre") +
  scale_fill_brewer(name = "Terminal", palette = "Set2") +
  ggtitle("Passengers Count by Airline and Terminal") +
  format_title +
  format_legend_title
```

### VI. Airlines

```{r united}
data %>%
  filter(code == "UA") %>%
  group_by(month, year) %>%
  summarise(Passengers = sum(pax)) %>%
  ggplot(aes(x = factor(month, labels = month.abb), y = year)) +
  geom_tile(aes(fill = Passengers)) + 
  scale_x_discrete(name = "Month") +
  scale_y_continuous(expand = c(0, 0), name = "Year", breaks = seq(min(data$year), max(data$year), by = 1)) +
  scale_fill_gradientn(colours = rev(heat.colors(10)), labels = comma) +
  theme_minimal() +
  ggtitle("United Airlines Passengers Count") +
  format_title +
  format_legend_title
```

```{r cathay}
data %>%
  filter(code == "CX") %>%
  group_by(month, year) %>%
  summarise(Passengers = sum(pax)) %>%
  ggplot(aes(x = factor(month, labels = month.abb), y = year)) +
  geom_tile(aes(fill = Passengers)) + 
  scale_x_discrete(name = "Month") +
  scale_y_continuous(expand = c(0, 0), name = "Year", breaks = seq(min(data$year), max(data$year), by = 1)) +
  scale_fill_gradientn(colours = rev(heat.colors(10)), labels = comma) +
  theme_minimal() +
  ggtitle("United Airlines Passengers Count") +
  format_title +
  format_legend_title
```

